### ISSUE TITLE
Samba4 Backup - tar issue!?

### ISSUE THREAD

**Issue by it2semi** [thctlo/samba4#7]
Hi!

I just tried the samba4 backup script and got an TAR error. 

./backup_samba4 --debug
Command checks : CMD_ECHO contains : /bin/echo
Command checks : CMD_SAMBA contains : /usr/sbin/samba
Command checks : CMD_TDBBACKUP contains : /usr/bin/tdbbackup
Command checks : CMD_LOGGER contains : /usr/bin/logger
Command checks : CMD_TAR contains : /bin/tar
Command checks : CMD_DIRNAME contains : /usr/bin/dirname
Command checks : CMD_CAT contains : /bin/cat
Command checks : CMD_GREP contains : /bin/grep
Command checks : CMD_AWK contains : /usr/bin/awk
Command checks : CMD_SED contains : /bin/sed
Command checks : CMD_DATE contains : /bin/date
Command checks : CMD_FIND contains : /usr/bin/find
Command checks : CMD_RM contains : /bin/rm
Command checks : CMD_GETFACL contains : /usr/bin/getfacl
Command checks : CMD_TAIL contains : /usr/bin/tail
Command checks : CMD_CUT contains : /usr/bin/cut
Command checks : CMD_WC contains : /usr/bin/wc
Command checks : CMD_AWK contains : /usr/bin/awk
Command checks : CMD_SORT contains : /usr/bin/sort
Starting backup with ./backup_samba4
Backupdate = 2019-10-02
Message: checking for previous backups of this day : private
Counter = 2
Message: setting date and counter : 2019-10-02-3 for  private
/bin/tar: The following options were used after any non-optional arguments in archive create or update mode.  These options are positional and affect only arguments that follow them.  Please, rearrange them properly.
/bin/tar: --exclude „*.ldb“ has no effect
/bin/tar: --exclude „*.tdb“ has no effect
/bin/tar: Beende mit Fehlerstatus aufgrund vorheriger Fehler

What I could do? Any advices?

best regards,
semi

**Comment by thctlo** [comment]
Hai, 

On what system is this?
And what is the tar version?

**Comment by it2semi** [comment]
Debian GNU/Linux 10
tar: 1.30+dfsg-6

**Comment by thctlo** [comment]
Hai, if fixed the issue, can you pull the modified version from github and test again. 

I'll keep this open untill you verified it also.

**Comment by thctlo** [comment]
fixed in commit : 926ff68ac79f6be4f60d3c9f1d0d0be044991db0

**Comment by it2semi** [comment]
checked it. same error :-(

**Comment by thctlo** [comment]
Hai, now its really fixed. I missed one thing. 
Can you verify again?

**Comment by it2semi** [comment]
thanks a lot for your work. but sorry, I still get an error. 

Command checks : CMD_ECHO contains : /bin/echo
Command checks : CMD_SAMBA contains : /usr/sbin/samba
Command checks : CMD_TDBBACKUP contains : /usr/bin/tdbbackup
Command checks : CMD_LOGGER contains : /usr/bin/logger
Command checks : CMD_TAR contains : /bin/tar
Command checks : CMD_DIRNAME contains : /usr/bin/dirname
Command checks : CMD_CAT contains : /bin/cat
Command checks : CMD_GREP contains : /bin/grep
Command checks : CMD_AWK contains : /usr/bin/awk
Command checks : CMD_SED contains : /bin/sed
Command checks : CMD_DATE contains : /bin/date
Command checks : CMD_FIND contains : /usr/bin/find
Command checks : CMD_RM contains : /bin/rm
Command checks : CMD_GETFACL contains : /usr/bin/getfacl
Command checks : CMD_TAIL contains : /usr/bin/tail
Command checks : CMD_CUT contains : /usr/bin/cut
Command checks : CMD_WC contains : /usr/bin/wc
Command checks : CMD_AWK contains : /usr/bin/awk
Command checks : CMD_SORT contains : /usr/bin/sort
Missing backup directory /mnt/data_sas/AD_Backups/reulisrv1
Will now create it.
Starting backup with ./backup_samba4
Backupdate = 2019-10-02
Message: checking for previous backups of this day : private
Counter =
Message: setting date and counter : 2019-10-02-0 for  private
/bin/tar: Status=0: Funktion stat fehlgeschlagen: Datei oder Verzeichnis nicht gefunden
/bin/tar: Beende mit Fehlerstatus aufgrund vorheriger Fehler

and in english ;-):
Function stat failed. File or Directory not found.

**Comment by thctlo** [comment]
Ah, i can read and speak german, so no problem there ;-) 
Ok, now i think, i know whats going on at your side, i'll verify it here. give me few min.

**Comment by thctlo** [comment]
Ok, took a bit longer, but now im sure it running fine ;-)

**Comment by it2semi** [comment]
Thanks! Works like a charm. Good work! 👍

**Comment by thctlo** [comment]
Great. thanks for the input. 
i'm closing this issue.
